### PR TITLE
Optionally supply a scenario ID to `create` to update a scenario instead

### LINKED ISSUE #93: Add possibility to add scenario-id to create_scenario
Currently it is not possible to update an existing scenario with an ESDL-file (other than using the create_with_context api). It would be awesome (and eventually necessary) to be able to do this with the create_scenario endpoint as well.

Steps:
- Define steps that need to be taken
- If more time is needed then 0.5 day, report back
- Otherwise, go for it whenever possible! :-)

### PR DESCRIPTION
**Pull request by noracato**
Quick fix.
We should actually:
- [ ] #95
- [ ] #96

Closes #93

### CODE REVIEW

**Comment by redekok** [comment]
Could it be the case that the app has some troubles with authentication rights? I think it won't allow me to modify a randomly created scenario because I'm not authored to (without valid credentials)? 

image

**Comment by noracato** [comment]
You can not communicate with scenario's you made when you were logged in indeed. Running ETE locally solves this. But yes, we need to add SSO support to the app indeed!

**Comment by redekok** [comment]
The KPI handler also caused some trouble which I've fixed in https://github.com/quintel/etm-esdl/commit/71c203284af50b0e9ebdb8444b11b0d93446e727. After, I managed to update an existing ETM scenario based on an ESDL file. However, when I try this twice in a row (with the same API session ID) I get the following error:

image

@noracato is this something we should fix before merging this PR?

**Comment by redekok** [comment]
LGTM now! 💯

**Pull request merged**
